### ISSUE TITLE
Temporary file not found

### ISSUE THREAD

**Issue by AurelieMLB** [zachcp/msaR#1]
Hello,

I am trying your package. Thanks for your work.

I tried the example code:
(https://cran.r-project.org/web/packages/msaR/vignettes/msaR.html)
library(msaR)
seqfile <- system.file("sequences","AHBA.aln", package="msaR")
msaR(seqfile, menu=F, overviewbox = F)

At this point my browser (firefox) opened and told me: 
"file not found: /tmp/Rtmpw64fvO/viewhtml31c94594a835/index.html."

I work on a Linux environment. I have double checked the /tmp is open in writing and reading for all.

Would you have an idea of what is happening and how to fix this please?

Many thanks

**Comment by AurelieMLB** [comment]
Hello,
Update:
I removed some the packages that I was importing "by default" and now I am passed that issue.
But, I have another issue: the html file that opens is all blank...
For reference (I do not know if it is related), I have a similar issue with d3Heatmap. I have the x and y axis but all the grid is blank. Heatmaply works perfectly though.
Any idea of what is happening please?
Any help would be really appreciated.
Many thanks

**Comment by AurelieMLB** [comment]
Hello again,
Apologies for spamming.
May I ask which version of R is necessary for Rmsa please?

Thank you!

**Comment by zachcp** [comment]
Hi Aureliemb,

I'm away so I can't properly troubleshoot this until the end of the week. But everything should work. If you are getting a partial load in the browser you may not be passing in any data. Did you try with your own sequences?

Zach cp

**Comment by AurelieMLB** [comment]
Hello,

Thanks for your answer.
I have used the sequences provided in the package. I got them by doing:
seqfile <- system.file("sequences","AHBA.aln", package="msaR")
I just checked. There is data in this file.
But the plot still comes back blank.... even though msaR gives no error/warning at all.

I did also tried with my sequences and the outcome is the same.

I am interested in any help, even next week :)

For reference, here are my session info:
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

locale:
 [1] LC_CTYPE=en_GB       LC_NUMERIC=C         LC_TIME=en_GB       
 [4] LC_COLLATE=en_GB     LC_MONETARY=en_GB    LC_MESSAGES=en_GB   
 [7] LC_PAPER=en_GB       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_GB LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] msaR_0.2.0

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.9 parallel_3.3.1  htmltools_0.3.6 yaml_2.1.14    
 [5] Rcpp_0.12.12    nlme_3.1-131    ape_4.1         grid_3.3.1     
 [9] jsonlite_1.5    digest_0.6.12   lattice_0.20-35


Many thanks
Aurelie

**Comment by zachcp** [comment]
Aurelie,

This works fine for me. Do you have a Javascript blocker in your browser by any chance? Are you using Rstudio (this should definitely display)? If you open up your browser's development tools do you get an error? I am guessing that your browser is blocking javascript or that there is a browser-incompatability problem although this works fine for me in  Chrome/Safari/Firefox. 



zach cp

**Comment by AurelieMLB** [comment]
Hello Zach,

Thank you so much for looking into this!
I will check the browser development tools. I will definitely keep you updated if I find something.

Best
Aurelie

**Comment by zachcp** [comment]
Aurelie,

Did you figure this out? I'm closing this -please reopen a new issue if you still have a problem.

zach cp

**Comment by AurelieMLB** [comment]
Hello,

No sorry...
I ended up using R studio with the last version of R and it works there but I have not persisted on Linux.

Many thanks for asking.
Aurelie
