### ISSUE TITLE
msaR function displays nothing

### ISSUE THREAD

**Issue by gauravdiwan89** [zachcp/msaR#14]
Hello,

Thanks for the great package. However, the rendering of alignments has stopped working. This is also happening on the [reference page](https://zachcp.github.io/msaR/articles/msaR.html) of the package. Will it be possible to check and fix this?

Thanks!

**Comment by gauravdiwan89** [comment]
Actually. I found a fix for this issue from [here](https://github.com/wilzbach/msa/issues/260#issuecomment-910364121)

You can just replace the term `!t instanceof Array||"at"in t` with `!t instanceof Array||"_byId"in t` in the `msa.js` file.

I hope this helps!

**Comment by zachcp** [comment]
also submitting updated package to CRAN. thanks for the fix.
