### ISSUE TITLE
Add phylogenetic tree next to MSA? 

### ISSUE THREAD

**Issue by alptaciroglu** [zachcp/msaR#7]
Thanks for your effort in developing the package (R version and the original one).

I was wondering if there is any chance to add the corresponding phylogenetic tree next to the visualized MSA for dynamic viewing using Shiny R. Thanks

**Comment by zachcp** [comment]
@alptaciroglu  I don't think there is exactly what you want - an integrated phylogenetic tree viewer with an MSA. If a static tree/MSA is good you can check out [ggtree](https://github.com/zachcp/phyloTreeWidget). If you want an htmlwidget tree you can try [phyloTreeWidget](https://github.com/zachcp/phyloTreeWidget) but i don't know of a nice R package that gives an integrated tree+msa.  

If `msa.js` has this ability and you provide a JS example, I may be able to help code it.

**Comment by alptaciroglu** [comment]
Yeah I was trying to find such an R package but dont think there is one. I really like the dynamic view of msaR and wrapping of msa package i.e. consensus sequence scoring, sequence logo that comes with.. 

I will definitely check msa.js let you know. Thanks a bunch!
