### ISSUE TITLE
msaR for amino acid sequences

### ISSUE THREAD

**Issue by haruosuz** [zachcp/msaR#8]
Dear Developer,

When the msaR function was applied to multiple alignment of protein sequences, it generated seqlogo not for amino acids but for nucleotides (A T G C) as shown in attachment.

[my_avrilcoghlan5_msaR.docx](https://github.com/zachcp/msaR/files/5540967/my_avrilcoghlan5_msaR.docx)

**Comment by zachcp** [comment]
@haruosuz , it looks like you can solve your issue by changing the color scheme. See below


```R

# your code
library(seqinr)
suppressMessages(library(Biostrings))
library(msa)
library(msaR)
library(ape)


retrieve_seqs_uniprot <- function(ACCESSION)  {
    read.fasta(file=paste0("http://www.uniprot.org/uniprot/",ACCESSION,".fasta"), seqtype="AA", strip.desc=TRUE)[[1]]
}

seqnames <- c("P06747", "P0C569", "O56773", "Q5VKP1") # Make a vector containing the names of the sequences
seqs <- lapply(seqnames,  retrieve_seqs_uniprot) # Retrieve the sequences and store them in list variable "seqs"

# write the sequences to a FASTA-format file
write.fasta(seqs, seqnames, file="phosphoproteins.fasta")

mySequences <- readAAStringSet(file = "phosphoproteins.fasta")

# Multiple Sequence Alignment using ClustalW
myAlignment <- msa(inputSeqs=mySequences, method="ClustalW")
## use default substitution matrix
writeXStringSet(unmasked(myAlignment), file = "myaln.fasta")
myaln <- read.alignment(file = "myaln.fasta", format = "fasta")


msaR(myaln, menu=F, overviewbox = F)

```

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1260667/99311964-5df56480-282b-11eb-8873-105ed43c71e9.png">


## Pass in a different Colorscheme

```r
msaR(myaln, menu=F, overviewbox = F, colorscheme = "clustal")

```
<img width="490" alt="image" src="https://user-images.githubusercontent.com/1260667/99312021-71083480-282b-11eb-912a-49ea301cf19e.png">

**Comment by haruosuz** [comment]
Thank you for your reply. I would be grateful if you could update the tutorials. The following R code is duplicate in Vignettes (https://cran.r-project.org/web/packages/msaR/vignettes/msaR.html):
```
msaR(seqfile, menu=F, overviewbox = F)
```

**Comment by zachcp** [comment]
@haruosuz  thats a good & reasonable addition.  See #9 .
